#!/bin/bash
# =============================================================================
# SOC Home Lab — Task 4: Linux auditd Configuration
# Host: Ubuntu Server VM (SIEM machine)
# Purpose: Configure kernel-level audit logging and ship to Elasticsearch
# =============================================================================

# THEORY: auditd vs Windows Security Log
# ----------------------------------------
# Windows Security Log: Generated by userspace LSASS/Security subsystem.
#   - Structured event IDs defined by Microsoft
#   - High-value but can be bypassed by privileged userspace processes
#
# Linux auditd: Hooks into the Linux KERNEL (since kernel 2.6)
#   - Records syscalls BEFORE they complete — kernel-enforced
#   - You write your own rules — flexible but requires knowledge
#   - auid field = audit UID = original login user, survives sudo/su
#     (Windows equivalent: SubjectLogonId / logon session tracking)
#   - Cannot be bypassed by userspace — the kernel itself records events
#
# Architecture:
#   Process → syscall → Kernel Audit Hook → kauditd → auditd → audit.log
#   Then: Elastic Agent (Auditd Manager) reads from kernel socket → Elasticsearch

# =============================================================================
# STEP 1: Install auditd
# =============================================================================

sudo apt update
sudo apt install -y auditd audispd-plugins

# auditd        = the daemon that receives kernel events and writes them
# audispd-plugins = dispatcher plugins for forwarding events

sudo systemctl enable auditd
sudo systemctl start auditd
sudo systemctl status auditd

# =============================================================================
# STEP 2: Review default config
# =============================================================================

# Main config — controls daemon behavior (rotation, disk space handling)
# /etc/audit/auditd.conf
#   log_file = /var/log/audit/audit.log
#   max_log_file = 8                      (MB per file)
#   num_logs = 5                          (rotated files kept)
#   space_left_action = SYSLOG            (what to do when disk fills)
#   admin_space_left_action = SUSPEND     (last resort)

# Rules location — auditd loads all .rules files from this directory
# /etc/audit/rules.d/

# =============================================================================
# STEP 3: Create SOC audit rules
# =============================================================================

# Rules types:
# Control rules (-b, -f, -e): configure the audit subsystem itself
# File watch rules (-w): watch files/dirs for specific permission access
#   -p w=write, a=append, r=read, x=execute
# Syscall rules (-a): trigger on kernel syscall events
#   -a always,exit = record when syscall exits (success or failure)
#   -F arch=b64 = filter for 64-bit architecture
#   -S = syscall name or number
#   -k = key (label for this rule, used to filter with ausearch)

cat << 'EOF' | sudo tee /etc/audit/rules.d/soc-lab.rules
## SOC Lab Audit Rules

## Control rules
-D                          # delete all existing rules (clean slate)
-b 8192                     # kernel buffer size for audit records
-f 1                        # failure mode: 1=log, 2=panic (halt system)

## Identity & privilege escalation
## MITRE: T1136 (Create Account), T1548 (Abuse Elevation Control)
-w /etc/passwd -p wa -k identity_change
-w /etc/shadow -p wa -k identity_change
-w /etc/group -p wa -k identity_change
-w /etc/gshadow -p wa -k identity_change
-w /etc/sudoers -p wa -k privilege_escalation
-w /etc/sudoers.d/ -p wa -k privilege_escalation

## PAM (Pluggable Authentication Modules) — how Linux does auth
-w /etc/pam.d/ -p wa -k pam_change

## setuid/setgid syscalls — process privilege changes
-a always,exit -F arch=b64 -S setuid -k setuid_call
-a always,exit -F arch=b64 -S setgid -k setgid_call

## Process execution — Linux equivalent of Windows Event ID 4688
## syscall execve = how every program is launched on Linux
-a always,exit -F arch=b64 -S execve -k process_execution
-a always,exit -F arch=b32 -S execve -k process_execution

## Network connections — process-attributed (complements Zeek)
## syscall connect = how a process initiates TCP/UDP connections
-a always,exit -F arch=b64 -S connect -k network_connect
-a always,exit -F arch=b32 -S connect -k network_connect

## Staging areas — common attacker file drop locations
## MITRE: T1074 (Data Staged)
-w /tmp/ -p wx -k staging_area
-w /dev/shm/ -p wx -k staging_area

## Persistence via cron
## MITRE: T1053.003 (Scheduled Task/Job: Cron)
-w /etc/cron.d/ -p wa -k cron_change
-w /etc/crontab -p wa -k cron_change
-w /var/spool/cron/ -p wa -k cron_change

## Kernel module loading — rootkit/persistence detection
## MITRE: T1547.006 (Boot or Logon Autostart: Kernel Modules and Extensions)
-w /sbin/insmod -p x -k kernel_module
-w /sbin/rmmod -p x -k kernel_module
-w /sbin/modprobe -p x -k kernel_module
-a always,exit -F arch=b64 -S init_module -S finit_module -k kernel_module_load

## SSH config changes
-w /etc/ssh/sshd_config -p wa -k ssh_config_change

## Lock rules (make immutable until reboot) — uncomment for production
## -e 2
EOF

# =============================================================================
# STEP 4: Load rules and verify
# =============================================================================

# augenrules compiles all .rules files in /etc/audit/rules.d/ and loads them
sudo augenrules --load

# List loaded rules
sudo auditctl -l

# Check audit subsystem status
# Should show: enabled 1, failure 1, backlog_limit 8192, lost 0
sudo auditctl -s

# =============================================================================
# STEP 5: Test and read audit logs
# =============================================================================

# Test identity_change rule by creating a user
sudo useradd testaudituser

# Search logs by key (-k = key label we set in our rules)
sudo ausearch -k identity_change | tail -30

# Reading an audit log record — key fields:
# type=SYSCALL          — the type of record
# msg=audit(ts:serial)  — timestamp and unique serial
# syscall=N             — syscall number (ausyscall N to look up)
# auid=N                — AUDIT UID = original login user (survives sudo/su)
#                         Windows equivalent: SubjectLogonId
# uid=N                 — current real UID
# euid=N                — effective UID (what process runs as)
# comm="name"           — command name
# exe="/path"           — full path to executable
# key="label"           — our rule label
# success=yes/no        — did the syscall succeed?

# Useful ausearch options:
# -k KEY        = filter by rule key
# -ts recent    = last 10 minutes
# -ts today     = today only
# -ui UID       = filter by user ID
# -m TYPE       = filter by record type (SYSCALL, PATH, USER_AUTH, etc.)
sudo ausearch -k process_execution -ts recent
sudo ausearch -k identity_change

# aureport — summary statistics
sudo aureport --summary         # overall summary
sudo aureport -x --summary      # most-executed commands
sudo aureport -l                # login events
sudo aureport -a                # anomaly report

# Clean up test user
sudo userdel testaudituser

# =============================================================================
# STEP 6: Fleet/Kibana — Auditd Manager Integration
# (UI steps — documented as comments)
# =============================================================================

# UI: Kibana → Fleet → Agent Policies → Linux Agent Policy
# UI: Click "Add integration" → search "Auditd Manager"
# UI: Click "Auditd Manager" → "Add Auditd Manager"
# UI: Configure:
#       Integration name: auditd-ubuntu-siem
#       Audit rules: (can paste rules here, or leave blank to use system rules)
#       Leave other defaults
# UI: "Save and continue" → "Save and deploy changes"

# HOW ELASTIC READS AUDITD:
# The Auditd Manager integration connects DIRECTLY to the kernel audit socket
# (AF_UNIX socket) — it does NOT read /var/log/audit/audit.log
# This is more real-time and efficient than file-based reading
# It may coexist with or replace auditd depending on config

# =============================================================================
# STEP 7: Verify in Kibana Discover
# =============================================================================

# UI: Kibana → Discover
# UI: Data view: logs-* or auditbeat-*
# UI: Filter: event.module: "auditd"
# UI: Or: auditd.data.key: "process_execution"
# Key ECS fields mapped from auditd:
#   auditd.data.syscall       = syscall number
#   auditd.data.auid          = audit UID (original login user)
#   auditd.data.key           = our rule key label
#   process.executable        = exe field
#   user.name                 = resolved username
#   event.outcome             = success/failure

# =============================================================================
# STEP 8: Detection Rule — /etc/passwd Modified
# =============================================================================

# UI: Kibana → Security → Rules → Create new rule → Custom Query
# Query:
#   event.module: "auditd" AND auditd.data.key: "identity_change"
# Name: "Linux - /etc/passwd Modified"
# Severity: High
# MITRE: TA0003 Persistence / T1136.001 Create Account: Local Account
# Save and enable

# =============================================================================
# STEP 9: Simulate attack and verify alert
# =============================================================================

# Simulate attacker creating a persistence account
sudo useradd attackersimuser
# Wait ~30 seconds
# UI: Kibana → Security → Alerts — should see alert fire
# Clean up:
sudo userdel attackersimuser

# =============================================================================
# KEY INTERVIEW CONCEPTS — Task 4 Summary
# =============================================================================

# Q: How does auditd differ from Windows Security Log?
# A: auditd hooks at the kernel level via the Linux Audit subsystem (since
#    kernel 2.6). It intercepts syscalls before they complete. Windows Security
#    Log is generated by the userspace LSASS/Security subsystem. auditd is
#    harder to bypass, but requires manual rule authoring.

# Q: What is auid and why does it matter?
# A: Audit UID — the original login UID, set at login and preserved even after
#    sudo or su. If auid=1001 and uid=0, a user logged in as UID 1001 escalated
#    to root. Without auid you'd only see uid=0 and lose attribution.

# Q: What is the difference between a file watch rule and a syscall rule?
# A: File watch (-w /path -p perms): watches a specific file/dir for specific
#    access types (read/write/exec/append). Syscall rule (-a always,exit -S):
#    watches for any invocation of a specific kernel syscall, optionally filtered
#    by user, program, or other criteria. Syscall rules are more general.

# Q: What is execve and why do we audit it?
# A: execve is the Linux syscall used to launch a new program — it replaces the
#    current process image with a new one. Every command you run goes through
#    execve. Auditing it = auditing all process execution, equivalent to Windows
#    Event ID 4688 (Process Creation) or Sysmon Event ID 1.