# =============================================================================
# SOC HOME LAB — TASK 2: WINDOWS EVENT LOG CHANNELS
# =============================================================================
# Target Host : Windows 10 VM (monitored endpoint)
# Fleet Policy: Windows Agent Policy
# Goal        : Enable Security, System, Application, and PowerShell Operational
#               channels. Configure audit policy. Ship all to Elasticsearch.
# Run as      : Administrator (PowerShell)
# Prereq      : Task 1 complete (Sysmon installed and shipping to Elastic)
# =============================================================================


# =============================================================================
# THEORY BLOCK 1: THE WINDOWS EVENT LOG ARCHITECTURE
# =============================================================================
# Windows does not have one log file. It has a hierarchy of named "channels"
# managed by the Windows Event Log service (WEvtSvc, svchost.exe).
#
# Each channel is registered by a "provider" (publisher). The provider declares
# its channel in a manifest (.man file) and registers it with Windows. The
# Event Log service then routes events from that provider into the correct
# channel.
#
# Channel types:
#   Classic    : Security, System, Application
#                These predate Vista. They use a simpler event format.
#   Operational: Microsoft-Windows-PowerShell/Operational
#                These use the modern ETW (Event Tracing for Windows) pipeline.
#
# The four channels and their purpose:
#
#   SECURITY
#     Owner  : Windows Security Reference Monitor (SRM) in the kernel
#              + LSASS (Local Security Authority Subsystem Service)
#     Purpose: Records authentication events, privilege use, account changes,
#              object access, policy changes.
#     Key    : Events here are generated by the KERNEL, not by apps. You need
#              "audit policy" configured for events to be generated at all.
#     Linux  : Closest equivalent is /var/log/auth.log + auditd
#
#   SYSTEM
#     Owner  : Windows kernel, device drivers, core OS services
#     Purpose: OS-level events — service start/stop, hardware failures,
#              driver loads, boot events.
#     Key    : Event ID 7045 (new service installed) lives here — this is a
#              common persistence and lateral movement indicator.
#     Linux  : Closest equivalent is /var/log/syslog or journald
#
#   APPLICATION
#     Owner  : User-mode applications (IIS, SQL Server, antivirus, etc.)
#     Purpose: Application-specific events. Highly variable — every app
#              decides what it logs here.
#     Key    : Less structured than Security. Useful for application errors
#              and some product-specific security events (IIS 401s, etc.).
#     Linux  : Closest equivalent is /var/log/application-name.log
#
#   MICROSOFT-WINDOWS-POWERSHELL/OPERATIONAL
#     Owner  : PowerShell engine
#     Purpose: Records script execution, module loads, remoting, errors.
#              This is the primary channel for PowerShell-based attack detection.
#     Key    : NOT enabled by default. Requires registry configuration.
#              Requires separate Fleet integration entry or custom channel config.
#     Linux  : No direct equivalent (bash doesn't have built-in structured
#              logging — you'd use auditd with execve rules instead)
# =============================================================================


# =============================================================================
# THEORY BLOCK 2: AUDIT POLICY — WHY EVENTS DON'T APPEAR WITHOUT IT
# =============================================================================
# This is a critical concept that many analysts miss.
#
# The Security event log is NOT like a normal application log. Events are only
# generated when:
#   1. The Windows SRM (kernel) decides an auditable event occurred, AND
#   2. The relevant "audit subcategory" is ENABLED in audit policy
#
# Without audit policy, the kernel simply doesn't generate the events.
# You can have Elastic Agent perfectly configured to read the Security channel
# and still get nothing — because there's nothing being written to it.
#
# Two layers of audit policy:
#
#   Basic audit policy (9 categories):
#     Set via: Local Security Policy > Audit Policy
#     Or:      auditpol /set /category:"..."
#     Legacy approach — predates Vista
#
#   Advanced audit policy (53 subcategories):
#     Set via: Local Security Policy > Advanced Audit Policy
#     Or:      auditpol /set /subcategory:"..."
#     Preferred — more granular, avoids enabling entire categories
#
# We always use the ADVANCED (subcategory) approach in detection engineering
# because the basic categories enable too much at once.
#
# Key subcategories for detection:
#   Logon             -> 4624 (success), 4625 (failure)
#   Logoff            -> 4634
#   Process Creation  -> 4688
#   User Account Mgmt -> 4720, 4722, 4724, 4726, 4728, 4738, 4740
#   Security Group Mgmt -> 4728, 4732, 4756
#   Special Logon     -> 4672 (admin token used at logon)
#   Sensitive Privilege Use -> 4673, 4674
# =============================================================================


# =============================================================================
# THEORY BLOCK 3: THE SIX EVENT IDs YOU MUST KNOW
# =============================================================================
#
# --- SECURITY CHANNEL ---
#
# Event ID 4624 — Account Logon Success
#   Generated when: Any account successfully authenticates
#   Key field: LogonType (tells you HOW the logon happened)
#
#   LogonType values:
#     2  = Interactive      (keyboard at console — normal local login)
#     3  = Network          (SMB, net use, file share — lateral movement source)
#     4  = Batch            (scheduled task ran — check for persistence)
#     5  = Service          (service account starting — service installation)
#     7  = Unlock           (workstation unlock — normal)
#     10 = RemoteInteractive (RDP session — high-value for RDP tracking)
#     11 = CachedInteractive (cached domain creds — offline domain logon)
#
#   Detection patterns:
#     - Workstation-to-workstation Type 3 logon = lateral movement
#     - Type 10 (RDP) from unexpected IP = external RDP access
#     - Type 5 at odd hours = suspicious service install
#     - Many 4624s from one source IP = pass-the-hash or brute force success
#
# Event ID 4625 — Account Logon Failure
#   Generated when: Authentication fails
#   Key field: SubStatus (tells you WHY it failed)
#
#   SubStatus values:
#     0xC000006A = Wrong password (account EXISTS — useful for spray detection)
#     0xC0000064 = Username not found (account DOESN'T exist — enumeration)
#     0xC000006F = Logon outside allowed hours (account policy violation)
#     0xC000006D = Generic auth failure (bad credentials)
#     0xC0000234 = Account locked out
#
#   Detection patterns:
#     - Same source IP, many 4625 in short time = brute force
#     - 0xC0000064 SubStatus = username enumeration
#     - Many 4625 across many usernames from one IP = password spray
#       (spray = one password tried against many accounts to avoid lockout)
#
# Event ID 4688 — Process Create (native Windows)
#   Generated when: Any new process spawns
#   Key fields: NewProcessName, CommandLine, ParentProcessName, SubjectUserName
#
#   How it differs from Sysmon Event ID 1:
#     4688: No hashes, command line requires registry key, native (no install)
#     Sysmon 1: SHA256 hash, command line always present, requires Sysmon install
#   With Sysmon installed, you have BOTH — 4688 for compatibility with rules
#   written against native Windows logging, Sysmon 1 for richer data.
#
#   Detection patterns:
#     - cmd.exe or powershell.exe spawned by Office apps (macro execution)
#     - wscript.exe or cscript.exe running .vbs or .js files
#     - powershell.exe with -enc flag (base64 encoded command = obfuscation)
#     - net.exe or net1.exe commands (user/group enumeration or modification)
#     - whoami.exe immediately after any process = attacker checking context
#
# Event ID 4720 — User Account Created
#   Generated when: A local user account is created
#   Key fields: SubjectUserName (who created it), TargetUserName (new account)
#
#   Detection patterns:
#     - Account created outside business hours = backdoor creation
#     - 4720 followed quickly by 4728 (added to security group) = privilege escalation
#     - Account with suspicious name (numbers, random chars) = attacker persistence
#     - Created by a non-admin account = potential privilege escalation
#
# --- POWERSHELL OPERATIONAL CHANNEL ---
#
# Event ID 4103 — Module Logging
#   Generated when: Any PowerShell pipeline executes (requires Module Logging enabled)
#   Records: The full command AND its output
#   Volume: HIGH — logs every pipeline execution
#   Value: Captures the OUTPUT of commands (useful for data exfil detection)
#
# Event ID 4104 — Script Block Logging
#   Generated when: PowerShell compiles a script block to execute
#   Records: The FULL TEXT of the script block, post-deobfuscation
#   Volume: MEDIUM — one event per script block
#   Value: Captures obfuscated scripts in their decoded form
#
#   This is the most important PowerShell detection event.
#   Attackers use base64 encoding, string concatenation, char arrays, etc.
#   to obfuscate PowerShell. 4104 captures the code AFTER Windows decodes it.
#
#   Example: Attacker runs:
#     powershell -enc SQBuAHYAbwBrAGUALQBNAGkAbQBpAGsAYQB0AHoA
#   Without 4104: You see an encoded blob
#   With 4104: You see: Invoke-Mimikatz
#
#   Detection patterns:
#     - ScriptBlockText contains: Invoke-Mimikatz, Invoke-Empire, PowerSploit
#     - ScriptBlockText contains: DownloadString, IEX, Invoke-Expression
#     - ScriptBlockText contains: -enc or FromBase64String (re-encoding in script)
#     - ScriptBlockText contains: net.webclient, WebRequest (download cradles)
# =============================================================================


# =============================================================================
# STEP 1: ENABLE ADVANCED AUDIT POLICY (GENERATES SECURITY CHANNEL EVENTS)
# =============================================================================
# Run as Administrator

# View current state of all audit subcategories
auditpol /get /category:*

# --- Logon / Logoff (generates 4624, 4625, 4634, 4647) ---
# Both success and failure for Logon (you want to catch both real logins
# AND failed attempts for brute force detection)
auditpol /set /subcategory:"Logon" /success:enable /failure:enable
auditpol /set /subcategory:"Logoff" /success:enable /failure:enable

# Special Logon (generates 4672 — admin token used)
# This fires when an account with admin privileges logs in.
# Useful for tracking privileged account usage.
auditpol /set /subcategory:"Special Logon" /success:enable /failure:enable

# --- Process Tracking (generates 4688, 4689) ---
# 4688 = process created, 4689 = process exited
# Enable both — exit events let you calculate process duration
auditpol /set /subcategory:"Process Creation" /success:enable /failure:enable
auditpol /set /subcategory:"Process Termination" /success:enable /failure:enable

# --- Account Management (generates 4720, 4722, 4724, 4726, 4728, 4738, 4740) ---
# User Account Management: create/delete/modify user accounts
auditpol /set /subcategory:"User Account Management" /success:enable /failure:enable
# Security Group Management: add/remove from security groups (4728, 4732, 4756)
auditpol /set /subcategory:"Security Group Management" /success:enable /failure:enable

# --- Privilege Use (generates 4673, 4674) ---
# Fires when a process tries to use a sensitive privilege (SeDebugPrivilege,
# SeTcbPrivilege, etc.). Useful for detecting privilege abuse.
# NOTE: This is NOISY. Enable only if you have the storage capacity.
# auditpol /set /subcategory:"Sensitive Privilege Use" /success:enable /failure:enable

# --- Verify all settings are applied ---
Write-Host "=== Audit Policy Verification ==="
auditpol /get /subcategory:"Logon"
auditpol /get /subcategory:"Process Creation"
auditpol /get /subcategory:"User Account Management"
auditpol /get /subcategory:"Security Group Management"
# Expected: Each shows "Success and Failure" in the Setting column


# =============================================================================
# STEP 2: ENABLE COMMAND LINE LOGGING IN 4688
# =============================================================================
# By default, 4688 shows the process name but NOT the command line arguments.
# This registry key enables full command line capture.
# Without this, 4688 is far less useful for detection.

reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
    /v ProcessCreationIncludeCmdLine_Enabled `
    /t REG_DWORD /d 1 /f

# Verify
$regVal = Get-ItemProperty `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
    -Name "ProcessCreationIncludeCmdLine_Enabled" `
    -ErrorAction SilentlyContinue
Write-Host "ProcessCreationIncludeCmdLine_Enabled = $($regVal.ProcessCreationIncludeCmdLine_Enabled)"
# Expected: 1


# =============================================================================
# STEP 3: ENABLE POWERSHELL SCRIPT BLOCK LOGGING (Event ID 4104)
# =============================================================================
# This is NOT enabled by default. Requires registry configuration.
# These keys may not exist — we create them if absent.

# Script Block Logging path
$sbPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging"
if (-not (Test-Path $sbPath)) {
    New-Item -Path $sbPath -Force | Out-Null
    Write-Host "Created ScriptBlockLogging registry key"
}

# EnableScriptBlockLogging = 1 -> log all script blocks
Set-ItemProperty -Path $sbPath -Name "EnableScriptBlockLogging" -Value 1 -Type DWord

# EnableScriptBlockInvocationLogging = 1 -> also log start/stop of each block
# More verbose — log both the block text AND when each block starts/stops
Set-ItemProperty -Path $sbPath -Name "EnableScriptBlockInvocationLogging" -Value 1 -Type DWord

Write-Host "Script Block Logging (4104) enabled."


# =============================================================================
# STEP 4: ENABLE POWERSHELL MODULE LOGGING (Event ID 4103)
# =============================================================================
# Module logging captures the full pipeline input/output.
# It logs every call to every PowerShell cmdlet.
# More verbose than 4104 but also captures output, not just input.

# Module logging path
$mlPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging"
if (-not (Test-Path $mlPath)) {
    New-Item -Path $mlPath -Force | Out-Null
    Write-Host "Created ModuleLogging registry key"
}

# EnableModuleLogging = 1
Set-ItemProperty -Path $mlPath -Name "EnableModuleLogging" -Value 1 -Type DWord

# Specify which modules to log — "*" means ALL modules
# This is a subkey containing module name entries
$mlModPath = "$mlPath\ModuleNames"
if (-not (Test-Path $mlModPath)) {
    New-Item -Path $mlModPath -Force | Out-Null
}
# The wildcard "*" catches everything — in a real env you might limit this
# to Microsoft.PowerShell.* and specific known-attack modules
Set-ItemProperty -Path $mlModPath -Name "*" -Value "*" -Type String

Write-Host "Module Logging (4103) enabled for all modules."


# =============================================================================
# STEP 5: VERIFY ALL REGISTRY SETTINGS
# =============================================================================

Write-Host "`n=== Script Block Logging Settings ==="
Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging"

Write-Host "`n=== Module Logging Settings ==="
Get-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\ModuleLogging"

Write-Host "`n=== Command Line in 4688 ==="
Get-ItemProperty `
    -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\Audit" `
    -Name "ProcessCreationIncludeCmdLine_Enabled"


# =============================================================================
# STEP 6: GENERATE TEST EVENTS FOR EACH EVENT ID
# =============================================================================

# --- Generate 4625 (Logon Failure) ---
# Authenticate with a wrong password to localhost — generates a local logon failure
Write-Host "`nGenerating 4625 (logon failure)..."
$cred = New-Object System.Management.Automation.PSCredential(
    "nonexistentuser_test",
    (ConvertTo-SecureString "WrongPass123" -AsPlainText -Force)
)
# This will fail — that's the point. Suppressing the error output.
Start-Process -FilePath "net.exe" `
    -ArgumentList "use \\localhost\IPC$ /user:nonexistentuser_test WrongPass123" `
    -Wait -WindowStyle Hidden 2>$null

# --- Generate 4688 (Process Create) ---
Write-Host "Generating 4688 (process create)..."
Start-Process -FilePath "powershell.exe" `
    -ArgumentList "-NoProfile -Command `"Get-Process | Select-Object -First 5`"" -Wait
Start-Process -FilePath "cmd.exe" -ArgumentList "/c whoami && hostname" -Wait

# --- Generate 4720 + 4726 (Account Create + Delete) ---
Write-Host "Generating 4720 (account create) and 4726 (account delete)..."
net user soc_testlab_acct S0cLabP@ss! /add /comment:"SOC lab test account - delete me"
Start-Sleep -Seconds 2
net user soc_testlab_acct /delete

# --- Generate 4104 (PowerShell Script Block) ---
Write-Host "Generating 4104 (script block logging)..."
# These script blocks will be captured by 4104
$scriptBlock1 = { Get-Process | Where-Object { $_.WorkingSet64 -gt 100MB } }
Invoke-Command -ScriptBlock $scriptBlock1

# Simulate a download cradle pattern (no actual download — just the pattern)
# In a real attack, this would be: IEX (New-Object Net.WebClient).DownloadString('...')
$scriptBlock2 = { $wc = New-Object System.Net.WebClient; Write-Host "WebClient created" }
Invoke-Command -ScriptBlock $scriptBlock2

# --- Verify events in each channel ---
Write-Host "`n=== Security Channel: Recent 4624 (Logon Success) ==="
Get-WinEvent -LogName Security |
    Where-Object { $_.Id -eq 4624 } |
    Select-Object -First 3 |
    ForEach-Object {
        $xml = [xml]$_.ToXml()
        [PSCustomObject]@{
            Time       = $_.TimeCreated
            EventID    = $_.Id
            LogonType  = ($xml.Event.EventData.Data | Where-Object Name -eq "LogonType")."#text"
            Account    = ($xml.Event.EventData.Data | Where-Object Name -eq "TargetUserName")."#text"
            SourceIP   = ($xml.Event.EventData.Data | Where-Object Name -eq "IpAddress")."#text"
        }
    } | Format-Table

Write-Host "`n=== Security Channel: Recent 4625 (Logon Failure) ==="
Get-WinEvent -LogName Security |
    Where-Object { $_.Id -eq 4625 } |
    Select-Object -First 3 |
    ForEach-Object {
        $xml = [xml]$_.ToXml()
        [PSCustomObject]@{
            Time       = $_.TimeCreated
            EventID    = $_.Id
            SubStatus  = ($xml.Event.EventData.Data | Where-Object Name -eq "SubStatus")."#text"
            Account    = ($xml.Event.EventData.Data | Where-Object Name -eq "TargetUserName")."#text"
            LogonType  = ($xml.Event.EventData.Data | Where-Object Name -eq "LogonType")."#text"
        }
    } | Format-Table

Write-Host "`n=== Security Channel: Recent 4688 (Process Create) ==="
Get-WinEvent -LogName Security |
    Where-Object { $_.Id -eq 4688 } |
    Select-Object -First 3 |
    ForEach-Object {
        $xml = [xml]$_.ToXml()
        [PSCustomObject]@{
            Time        = $_.TimeCreated
            Process     = ($xml.Event.EventData.Data | Where-Object Name -eq "NewProcessName")."#text"
            CmdLine     = ($xml.Event.EventData.Data | Where-Object Name -eq "CommandLine")."#text"
            ParentProc  = ($xml.Event.EventData.Data | Where-Object Name -eq "ParentProcessName")."#text"
        }
    } | Format-Table

Write-Host "`n=== Security Channel: 4720 (Account Created) ==="
Get-WinEvent -LogName Security |
    Where-Object { $_.Id -eq 4720 } |
    Select-Object -First 2 |
    Format-List TimeCreated, Message

Write-Host "`n=== PowerShell/Operational: 4104 (Script Block) ==="
Get-WinEvent -LogName "Microsoft-Windows-PowerShell/Operational" |
    Where-Object { $_.Id -eq 4104 } |
    Select-Object -First 5 |
    ForEach-Object {
        $xml = [xml]$_.ToXml()
        [PSCustomObject]@{
            Time            = $_.TimeCreated
            ScriptBlockText = ($xml.Event.EventData.Data |
                Where-Object Name -eq "ScriptBlockText")."#text" |
                Select-Object -First 1
        }
    } | Format-List


# =============================================================================
# STEP 7: CHECK CHANNEL SIZE AND VOLUME BREAKDOWN
# =============================================================================

# Check current log size and max size for each channel
Write-Host "`n=== Event Log Channel Sizes ==="
$channels = @("Security", "System", "Application", "Microsoft-Windows-PowerShell/Operational")
foreach ($ch in $channels) {
    $log = Get-WinEvent -ListLog $ch -ErrorAction SilentlyContinue
    if ($log) {
        Write-Host ("{0,-50} Size: {1,8:N0} KB  Max: {2,8:N0} KB  Records: {3,6}" -f
            $ch,
            [math]::Round($log.FileSize / 1KB),
            [math]::Round($log.MaximumSizeInBytes / 1KB),
            $log.RecordCount)
    }
}

# Identify the noisiest Event IDs in the Security channel (last hour)
Write-Host "`n=== Security Channel: Top Event IDs by Volume (last 1 hour) ==="
$cutoff = (Get-Date).AddHours(-1)
Get-WinEvent -LogName Security -ErrorAction SilentlyContinue |
    Where-Object { $_.TimeCreated -gt $cutoff } |
    Group-Object Id |
    Sort-Object Count -Descending |
    Select-Object -First 15 |
    Format-Table @{L="EventID";E={$_.Name}}, Count -AutoSize
# Use this output to decide what to EXCLUDE in your Elastic Agent config
# Common noisy events to consider excluding: 4634 (logoff), 5156/5158 (firewall)


# =============================================================================
# STEP 8: FLEET / KIBANA UI STEPS (DOCUMENT AS COMMENTS)
# =============================================================================

# ----------------------------------------------------------
# ADDING POWERSHELL OPERATIONAL CHANNEL TO FLEET:
# ----------------------------------------------------------
# 1. Open Kibana → Fleet → Agent Policies → "Windows Agent Policy"
# 2. Find the existing "Windows" integration → click to edit it
# 3. Look for the custom/additional event log channel section
# 4. Add: Microsoft-Windows-PowerShell/Operational
#         (exact name — case doesn't matter but spelling does)
# 5. Save and deploy changes
# 6. Fleet pushes new config to Windows agent (30-60 sec)
#
# IF the Windows integration doesn't support adding custom channels:
# 1. Add a new integration: "Custom Windows Event Log"
# 2. Channel Name: Microsoft-Windows-PowerShell/Operational
# 3. Dataset Name: windows.powershell_operational
# 4. Leave Event ID filter blank (collect all) or specify: 4103,4104
# 5. Save and deploy
#
# VERIFYING EXISTING SECURITY/SYSTEM/APPLICATION CHANNELS:
# (Already configured per your context — verify they're working)
# 1. Kibana → Discover
# 2. Query: winlog.channel: "Security" → should return events
# 3. Query: winlog.channel: "System" → should return events
# 4. Query: winlog.channel: "Application" → should return events
# ----------------------------------------------------------


# =============================================================================
# STEP 9: KIBANA KQL QUERIES (SAVE THESE)
# =============================================================================

# ----------------------------------------------------------
# All Security channel events from Windows VM:
#   winlog.channel: "Security"
#
# Successful logons — all:
#   event.code: "4624"
#
# Successful RDP logons only (LogonType 10):
#   event.code: "4624" AND winlog.event_data.LogonType: "10"
#
# Network logons only (lateral movement hunting):
#   event.code: "4624" AND winlog.event_data.LogonType: "3"
#
# All logon failures:
#   event.code: "4625"
#
# Logon failures — wrong password (account exists):
#   event.code: "4625" AND winlog.event_data.SubStatus: "0xC000006A"
#
# Logon failures — username doesn't exist (enumeration):
#   event.code: "4625" AND winlog.event_data.SubStatus: "0xC0000064"
#
# Process create — any PowerShell (4688):
#   event.code: "4688" AND winlog.event_data.NewProcessName: *powershell*
#
# Process create — encoded command (obfuscation indicator):
#   event.code: "4688" AND winlog.event_data.CommandLine: *-enc*
#
# Process create — Office spawning shell (macro execution):
#   event.code: "4688" AND winlog.event_data.ParentProcessName: *WINWORD*
#     AND winlog.event_data.NewProcessName: (*cmd* OR *powershell* OR *wscript*)
#
# User account created:
#   event.code: "4720"
#
# New service installed (System channel — persistence):
#   event.code: "7045" AND winlog.channel: "System"
#
# PowerShell script block — all:
#   event.code: "4104" AND winlog.channel: "Microsoft-Windows-PowerShell/Operational"
#
# PowerShell script block — download cradle patterns:
#   event.code: "4104" AND winlog.event_data.ScriptBlockText: (*DownloadString* OR *IEX* OR *WebClient*)
#
# PowerShell script block — known tool signatures:
#   event.code: "4104" AND winlog.event_data.ScriptBlockText: (*Mimikatz* OR *Invoke-Empire* OR *PowerSploit*)
# ----------------------------------------------------------


# =============================================================================
# INTERVIEW PREP — KEY CONCEPTS TO BE ABLE TO EXPLAIN
# =============================================================================
#
# Q: Why do Security channel events require audit policy?
# A: The Security channel is written by the Windows kernel SRM, not by a
#    user-mode application. The kernel only generates audit events when the
#    relevant subcategory is enabled in audit policy. Without it, nothing is
#    written. auditpol.exe or Group Policy configures which subcategories are
#    active. In enterprise environments, this is set via GPO and pushed to all
#    machines — if a machine's audit policy is misconfigured, you get a blind spot.
#
# Q: What's the difference between basic and advanced audit policy?
# A: Basic audit policy has 9 broad categories (Logon/Logoff, Object Access,
#    etc.). Advanced audit policy has 53 subcategories within those categories.
#    Always use advanced (subcategory) audit policy — it's more granular and
#    avoids enabling too much at once. You want "Logon" specifically, not the
#    entire "Logon/Logoff" category, which also includes noisy events.
#
# Q: Why is 4625 Sub Status more useful than just the failure count?
# A: Sub Status tells you WHY auth failed. 0xC0000064 means the username
#    doesn't exist — if you see this with many different usernames from one IP,
#    that's username enumeration. 0xC000006A means bad password on a valid
#    account — that's password spraying or brute force. Same event ID,
#    completely different attacker behavior.
#
# Q: What is PowerShell Script Block Logging and why does it matter?
# A: Event ID 4104 captures the full text of every PowerShell script block
#    AFTER Windows deobfuscates it. Attackers heavily obfuscate PS code with
#    base64 encoding, string concatenation, char arrays, etc. Without 4104,
#    you see an opaque blob. With 4104, Windows has already decoded it for
#    execution, and you see the actual malicious commands.
#
# Q: What's LogonType 3 and why do you hunt it for lateral movement?
# A: LogonType 3 is a network logon — authentication over the network (SMB,
#    net use, WMI, etc.). Legitimate Type 3 logons happen from users to file
#    servers. Suspicious Type 3: a workstation authenticating to another
#    workstation — workstations don't normally do this. If you see W1 -> W2
#    Type 3, that's classic lateral movement (PsExec, WMI, etc.).
#
# Q: How does 4688 compare to Sysmon Event ID 1?
# A: Both log process creation. 4688 is native (no install needed), always
#    present, but requires audit policy and a registry key to get command lines,
#    and provides no file hashes. Sysmon ID 1 requires Sysmon installation,
#    but gives you SHA256 hashes, always-on command lines, and ProcessGUID for
#    correlation. In a real SOC, you'd have both — some detection rules are
#    written against 4688, others against Sysmon data.


# =============================================================================
# END OF TASK 2
# Next: Task 3 — Install Zeek on Ubuntu SIEM VM and ship conn.log, dns.log,
#               http.log to Elastic. Learn what Zeek is, network vs host
#               visibility, and conn.log field meanings.
# =============================================================================